define(['require'], function(require) {
    /**
     * Routing configuration generated by Appery.io
     */
    /**
     * Default route
     * @type {{redirectTo: string}}
     */
    var default_route = {
        redirectTo: '/Screen1.html'
    };
    /**
     * Routing configuration object
     * @property {object} default                               - Default routing configuration
     * @property {string} default.redirectTo                    - Default routing URL
     * @property {object} when                                  - Routing configuration for different URLs
     * @property {object} when./                                - Routing configuration for "/" URL
     * @property {string} when./.redirectTo                     - Redirect to default routing URL
     * @property {object} when["/Screen1.html"]    - Routing configuration for /Screen1.html URL
     * @property {string} when["/Screen1.html"].c  - Controller for /Screen1.html URL
     * @property {string} when["/Screen1.html"].t  - Template for /Screen1.html URL
     * @property {string[]} when["/Screen1.html"].d  - Dependencies for /Screen1.html URL
     * @property {object} when["/Home.html"]    - Routing configuration for /Home.html URL
     * @property {string} when["/Home.html"].c  - Controller for /Home.html URL
     * @property {string} when["/Home.html"].t  - Template for /Home.html URL
     * @property {string[]} when["/Home.html"].d  - Dependencies for /Home.html URL
     * @property {object} when["/Ranking.html"]    - Routing configuration for /Ranking.html URL
     * @property {string} when["/Ranking.html"].c  - Controller for /Ranking.html URL
     * @property {string} when["/Ranking.html"].t  - Template for /Ranking.html URL
     * @property {string[]} when["/Ranking.html"].d  - Dependencies for /Ranking.html URL
     * @property {object} when["/Input.html"]    - Routing configuration for /Input.html URL
     * @property {string} when["/Input.html"].c  - Controller for /Input.html URL
     * @property {string} when["/Input.html"].t  - Template for /Input.html URL
     * @property {string[]} when["/Input.html"].d  - Dependencies for /Input.html URL
     * @property {object} when["/LL.html"]    - Routing configuration for /LL.html URL
     * @property {string} when["/LL.html"].c  - Controller for /LL.html URL
     * @property {string} when["/LL.html"].t  - Template for /LL.html URL
     * @property {string[]} when["/LL.html"].d  - Dependencies for /LL.html URL
     * @property {object} when["/INL.html"]    - Routing configuration for /INL.html URL
     * @property {string} when["/INL.html"].c  - Controller for /INL.html URL
     * @property {string} when["/INL.html"].t  - Template for /INL.html URL
     * @property {string[]} when["/INL.html"].d  - Dependencies for /INL.html URL
     * @property {object} when["/Votingcomplete.html"]    - Routing configuration for /Votingcomplete.html URL
     * @property {string} when["/Votingcomplete.html"].c  - Controller for /Votingcomplete.html URL
     * @property {string} when["/Votingcomplete.html"].t  - Template for /Votingcomplete.html URL
     * @property {string[]} when["/Votingcomplete.html"].d  - Dependencies for /Votingcomplete.html URL
     * @property {object} when["/Invitetoevent.html"]    - Routing configuration for /Invitetoevent.html URL
     * @property {string} when["/Invitetoevent.html"].c  - Controller for /Invitetoevent.html URL
     * @property {string} when["/Invitetoevent.html"].t  - Template for /Invitetoevent.html URL
     * @property {string[]} when["/Invitetoevent.html"].d  - Dependencies for /Invitetoevent.html URL
     * @property {object} when["/Weekendactivities.html"]    - Routing configuration for /Weekendactivities.html URL
     * @property {string} when["/Weekendactivities.html"].c  - Controller for /Weekendactivities.html URL
     * @property {string} when["/Weekendactivities.html"].t  - Template for /Weekendactivities.html URL
     * @property {string[]} when["/Weekendactivities.html"].d  - Dependencies for /Weekendactivities.html URL
     * @property {object} when["/Invitetocontribute.html"]    - Routing configuration for /Invitetocontribute.html URL
     * @property {string} when["/Invitetocontribute.html"].c  - Controller for /Invitetocontribute.html URL
     * @property {string} when["/Invitetocontribute.html"].t  - Template for /Invitetocontribute.html URL
     * @property {string[]} when["/Invitetocontribute.html"].d  - Dependencies for /Invitetocontribute.html URL
     * @property {object} when["/Events.html"]    - Routing configuration for /Events.html URL
     * @property {string} when["/Events.html"].c  - Controller for /Events.html URL
     * @property {string} when["/Events.html"].t  - Template for /Events.html URL
     * @property {string[]} when["/Events.html"].d  - Dependencies for /Events.html URL
     * @property {object} when["/Prof.html"]    - Routing configuration for /Prof.html URL
     * @property {string} when["/Prof.html"].c  - Controller for /Prof.html URL
     * @property {string} when["/Prof.html"].t  - Template for /Prof.html URL
     * @property {string[]} when["/Prof.html"].d  - Dependencies for /Prof.html URL
     * @property {object} when["/Youhavechosen.html"]    - Routing configuration for /Youhavechosen.html URL
     * @property {string} when["/Youhavechosen.html"].c  - Controller for /Youhavechosen.html URL
     * @property {string} when["/Youhavechosen.html"].t  - Template for /Youhavechosen.html URL
     * @property {string[]} when["/Youhavechosen.html"].d  - Dependencies for /Youhavechosen.html URL
     * @property {object} when["/Sanfran.html"]    - Routing configuration for /Sanfran.html URL
     * @property {string} when["/Sanfran.html"].c  - Controller for /Sanfran.html URL
     * @property {string} when["/Sanfran.html"].t  - Template for /Sanfran.html URL
     * @property {string[]} when["/Sanfran.html"].d  - Dependencies for /Sanfran.html URL

     * @property {object} otherwise                             - Routing configuration for another URL
     * @property {object} otherwise.redirectTo                  - Redirect to default routing URL
     * @property {object} route_names                           - Route aliases
     * @property {string} route_names.["Screen1"]  - "Screen1" is an alias for "/Screen1.html" routing
     * @property {string} route_names.["Home"]  - "Home" is an alias for "/Home.html" routing
     * @property {string} route_names.["Ranking"]  - "Ranking" is an alias for "/Ranking.html" routing
     * @property {string} route_names.["Input"]  - "Input" is an alias for "/Input.html" routing
     * @property {string} route_names.["LL"]  - "LL" is an alias for "/LL.html" routing
     * @property {string} route_names.["INL"]  - "INL" is an alias for "/INL.html" routing
     * @property {string} route_names.["Votingcomplete"]  - "Votingcomplete" is an alias for "/Votingcomplete.html" routing
     * @property {string} route_names.["Invitetoevent"]  - "Invitetoevent" is an alias for "/Invitetoevent.html" routing
     * @property {string} route_names.["Weekendactivities"]  - "Weekendactivities" is an alias for "/Weekendactivities.html" routing
     * @property {string} route_names.["Invitetocontribute"]  - "Invitetocontribute" is an alias for "/Invitetocontribute.html" routing
     * @property {string} route_names.["Events"]  - "Events" is an alias for "/Events.html" routing
     * @property {string} route_names.["Prof"]  - "Prof" is an alias for "/Prof.html" routing
     * @property {string} route_names.["Youhavechosen"]  - "Youhavechosen" is an alias for "/Youhavechosen.html" routing
     * @property {string} route_names.["Sanfran"]  - "Sanfran" is an alias for "/Sanfran.html" routing

     */
    return {
        default: default_route,
        when: {
            '/': default_route,
            '/Screen1.html': {
                c: '$signup/signupController',
                t: '$signup/signupTemplate.html',
                d: []
            },
            '/Home.html': {
                c: '$Home/HomeController',
                t: '$Home/HomeTemplate.html',
                d: []
            },
            '/Ranking.html': {
                c: '$Ranking/RankingController',
                t: '$Ranking/RankingTemplate.html',
                d: []
            },
            '/Input.html': {
                c: '$Input/InputController',
                t: '$Input/InputTemplate.html',
                d: []
            },
            '/LL.html': {
                c: '$LL/LLController',
                t: '$LL/LLTemplate.html',
                d: []
            },
            '/INL.html': {
                c: '$INL/INLController',
                t: '$INL/INLTemplate.html',
                d: []
            },
            '/Votingcomplete.html': {
                c: '$Votingcomplete/VotingcompleteController',
                t: '$Votingcomplete/VotingcompleteTemplate.html',
                d: []
            },
            '/Invitetoevent.html': {
                c: '$Invitetoevent/InvitetoeventController',
                t: '$Invitetoevent/InvitetoeventTemplate.html',
                d: []
            },
            '/Weekendactivities.html': {
                c: '$Weekendactivities/WeekendactivitiesController',
                t: '$Weekendactivities/WeekendactivitiesTemplate.html',
                d: []
            },
            '/Invitetocontribute.html': {
                c: '$Invitetocontribute/InvitetocontributeController',
                t: '$Invitetocontribute/InvitetocontributeTemplate.html',
                d: []
            },
            '/Events.html': {
                c: '$Events/EventsController',
                t: '$Events/EventsTemplate.html',
                d: []
            },
            '/Prof.html': {
                c: '$Prof/ProfController',
                t: '$Prof/ProfTemplate.html',
                d: []
            },
            '/Youhavechosen.html': {
                c: '$Youhavechosen/YouhavechosenController',
                t: '$Youhavechosen/YouhavechosenTemplate.html',
                d: []
            },
            '/Sanfran.html': {
                c: '$Sanfran/SanfranController',
                t: '$Sanfran/SanfranTemplate.html',
                d: []
            }
        },
        otherwise: default_route,
        route_names: {
            'Screen1': '/Screen1.html',
            'Home': '/Home.html',
            'Ranking': '/Ranking.html',
            'Input': '/Input.html',
            'LL': '/LL.html',
            'INL': '/INL.html',
            'Votingcomplete': '/Votingcomplete.html',
            'Invitetoevent': '/Invitetoevent.html',
            'Weekendactivities': '/Weekendactivities.html',
            'Invitetocontribute': '/Invitetocontribute.html',
            'Events': '/Events.html',
            'Prof': '/Prof.html',
            'Youhavechosen': '/Youhavechosen.html',
            'Sanfran': '/Sanfran.html'
        }
    };
});