define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for LL generated by Appery.io
         * @module LL
         */
        APP.controller('LL', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
            };
        }
    });